### ISSUE TITLE
Always-on-Display doesn't work.

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/meta-tetra-hybris#12]
Always-on-Display isn't functional on `tetra`. The cause is very simple: We only support Always-on-Display for the HWcomposer 1.4 and 1.5 HAL API. `tetra` only supports up to 1.3.

I have already tried to find a possible solution. Here are some of my observations.
The PowerHAL(`power.bcm_java.so`) is responsible for entering DOZE_SUSPEND mode(AOD mode).
The kernel has a `special mode` that is actually referred to, this is the ambient mode display.
The `special mode` is activated  by writing `1` to `/sys/devices/platform/3c200000.kona-fb/panel_mode`. Normally the PowerHAL is responsible for this.
A similar thing is also available for the touch screen, though I haven't looked into this specific thing.
It appears that the regular DOZE and DOZE_SUSPEND are still used in the hwcomposer service (the higher level Java service). Though this does not actually set the blanking to 2 or 3. Still blanking value of 0 is used. (0 = screen on).
In fact, the screen should never blank,vsync_suspend, etc when entering aod mode. This will turn off the screen.

From the looks of it the way it works is as follows:
- Screen dims
- Screens enters special mode. (Controlled by PowerHAL)
- Backlight turns off.
- Screen is now in ambient mode, safe to deep sleep.

My guess right now is that we must call a function in the PowerHAL to enable Always-on-Display. I am not sure which one. I will have to analyze the decompiled Android code for this :smile:

It is also a bit difficult to full check everything as the watch never enters deep sleep mode. (Not related to this issue, seems Bluetooth related).

I will update this issue once I find more information on how to solve this issue.

**Comment by MagneFire** [comment]
Progress update!

The main challenge in the previous post was to let the screen enter special mode, which, we know, is handled by the PowerHAL.

I started looking into two things: logs and (partially) decompiled code.

## Logs

### Missing message in logcat
Both `logcat`s on AsteroidOS and Android have an identical start:
```
01-26 23:31:26.034   491   491 I BRCM PowerHAL: BRCM PowerHAL: ************* entry *********************
01-26 23:31:26.034   491   491 E libdev-util: Unable to open '/sys/class/input/mice/name'
01-26 23:31:26.034   491   491 E libdev-util: Unable to open '/sys/class/input/event0/name'
01-26 23:31:26.034   491   491 E libdev-util: Unable to open '/sys/class/input/event1/name'
01-26 23:31:26.035   491   491 E libdev-util: Unable to open '/sys/class/input/event2/name'
01-26 23:31:26.035   491   491 E libdev-util: Unable to open '/sys/class/input/event3/name'
01-26 23:31:26.035   491   491 E BRCM PowerHAL: 'synaptics_dsx' device touch found at '/sys/class/input/input1/'
```

Then after some time the following appears in the `logcat` on Android:
```
01-26 23:31:46.079   491   782 I BRCM PowerHAL: BRCM PowerHAL: Setup Complete 
```
This is missing from the AsteroidOS backend!

### Special mode
When the display transitions to ambient mode the following is observed in `dmesg`:
```
Jan 27 19:56:07 tetra kernel: kona_fb_panel_mode_store:1053 panel mode 1
Jan 27 19:56:07 tetra kernel: synaptics_dsx_i2c 3-0020: synaptics_rmi4_f11_wg: enable 1
Jan 27 19:56:07 tetra kernel: synaptics_dsx_i2c 3-0020: Setting touch to doze
```
This is completely missing on AsteroidOS. As per the previous post, this means that the PowerHAL doesn't write to the appropriate sysfs path. Or PowerHAL ignoring `setInteractive` requests.

## Solutions

### PowerHAL: Setup Complete
The PowerHAL is mainly called by the `PowerManagerService`. The basic flow from low-level to higher-level is: PowerHAL -> JNI interface -> Android Java service.
As per previous debugging, this is ClockworkAmbient is an important piece of the puzzle. But this time `services.odex` contains the actual PowerManagerService.
Looking at the `smali` code reveals that it sets a couple of PowerHAL related settings:
```
Set PowerHint (2, 0), 2 = POWER_HINT_INTERACTION
Set PowerHint (5, 0), 5 = POWER_HINT_LOW_POWER
Set PowerHint (5, 1)

Set Feature(1, 0) 1 = POWER_FEATURE_DOUBLE_TAP_TO_WAKE
```
It turns out that any PowerHint will actually output `PowerHAL: Setup Complete`. In this case adding the following (to qt5-qpa-hwcomposer-plugin) will present the message:
```c
pwr_module->powerHint(pwr_module, POWER_HINT_INTERACTION, NULL);
```

### Fixing special-mode
This one was more tricky, initially looking into the decompiled assembly code didn't reveal anything useful, mainly due to me lacking some experience with ARM assembly code. I could not find a connections to the strings and the actual code connected to that.
So I moved to a different method of obtaining decompiled code: https://retdec.com/.
This framework is excellent! It actually write pseudo C code, which makes the behavior of the PowerHAL easier to understand.

Here is the code snippet of the decompiled code that sets `panel_mode`:
```c
int32_t function_d1c(int32_t a1, int32_t a2) {
    int32_t v1 = *(int32_t *)-0x46cfffb5; // 0xd2c
    int32_t v2 = 0; // 0xd36
    int32_t v3 = a2; // 0xd36
    int32_t v4; // 0xd1c
    int32_t v5; // 0xd1c
    int32_t v6; // 0xd1c
    int32_t v7; // 0xd3a
    if (function_ab0() == 0) {
        goto lab_0xe50;
    } else {
        // 0xd3a
        v7 = a1 + 144;
        function_940(v7);
        function_b80(a1);
        if (a2 == 0) {
            // 0xdb4
            function_928(4, "BRCM PowerHAL", &g35, (int32_t)"BRCM PowerHAL");
            int32_t v8; // bp-120, 0xd1c
            if (function_958("persist.sys.disable_ambient", &v8, 0) < 1) {
                goto lab_0xde0;
            } else {
                // 0xdd2
                if (function_964(&v8, "true", 4) == 0) {
                    goto lab_0xe02;
                } else {
                    goto lab_0xde0;
                }
            }
        } else {
            // 0xd52
            function_928(4, "e", (int32_t *)"%s: set interactive --> screen on\n", (int32_t)"e");
            function_b1c("/sys/devices/platform/3c200000.kona-fb/panel_mode", &g33);
            function_b1c("0", (int32_t *)(a1 + 163));
            function_b1c("/sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load", &g29);
            function_b1c("/sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay", &g28);
            function_b1c("/sys/devices/system/cpu/cpufreq/interactive/timer_rate", &g27);
            int32_t v9 = a1 + 184;
            v5 = v9;
            v4 = 2;
            v6 = (int32_t)"on";
            v3 = 0;
            if (*(char *)v9 == 0) {
                goto lab_0xe4a;
            } else {
                goto lab_0xe46;
            }
        }
    }
  lab_0xe50:;
    int32_t result = v2; // 0xe56
    if (v1 != *(int32_t *)-0x46cfffb5) {
        // 0xe58
        result = function_8ec(v2, v3, v1);
    }
    // 0xe5c
    return result;
  lab_0xde0:;
    int32_t v10 = function_904((int32_t)"/sys/devices/platform/3c200000.kona-fb/panel_mode", 0, (int32_t)&g36, 1); // 0xdec
    if (v10 < 0) {
        // 0xdf4
        function_928(6, "e", (int32_t *)"LCD failed to enter ambient.", 1);
    }
    goto lab_0xe02;
  lab_0xe4a:
    // 0xe4a
    v2 = function_94c(v7);
    goto lab_0xe50;
  lab_0xe46:
    // 0xe46
    function_904(v5, (int32_t)&g34, v6, v4);
    v3 = &g34;
    goto lab_0xe4a;
  lab_0xe02:
    // 0xe02
    function_b1c("/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq", (int32_t *)(a1 + 148));
    function_b1c("0", (int32_t *)"95");
    function_b1c("0", (int32_t *)"40000");
    function_b1c("\n", (int32_t *)"20000");
    int32_t v11 = a1 + 184;
    v5 = v11;
    v4 = 4;
    v6 = (int32_t)"doze";
    v3 = (int32_t)"20000";
    if (*(char *)v11 == 0) {
        goto lab_0xe4a;
    } else {
        goto lab_0xe46;
    }
}
```
A direct link between this code and the `setInteractive` function in PowerHAL isn't actually clearly visible. Which I guess isn't really important, as we know already that it is very likely that `setInteractive` is the responsible function in the PowerHAL (I already did some small test just passing a range of number to any of the available PowerHAL functions, no result).

Note in the code above that there is only one branch where `/sys/devices/platform/3c200000.kona-fb/panel_mode` isn't actually used, the very first `if` condition:
```c
    if (function_ab0() == 0) {
        goto lab_0xe50;
    } else {
```
Hmm, very interesting indeed :smile:. This function has the following contents:
```c
int32_t function_ab0(void) {
    int32_t * v1 = (int32_t *)g46; // 0xabe
    int32_t v2 = *v1; // 0xabe
    int32_t v3 = function_8bc("/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor", &g24); // 0xac6
    if (v3 != 0) {
        // 0xace
        int32_t v4; // bp-36, 0xab0
        function_8c8(v3, "%s", &v4);
        function_8d4(&v4, &g25);
        function_8e0(v3);
    }
    int32_t v5 = *v1; // 0xaf8
    int32_t result = 0; // 0xafc
    if (v2 != v5) {
        // 0xafe
        result = function_8ec(0, v5, v2);
    }
    // 0xb02
    return result;
}
```
You might think that the `function_8bc` will be useful here, but it really isn't:
```c
int32_t function_8bc(char * a1, int32_t * a2) {
    // 0x8bc
    return function_f0c02810();
}
```
This is where the *partially* decompiled statement came from.

Anyway, the `/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor` is another hint at something we can look into.
It looks like `android-init` sets this to `ondemand`: https://github.com/AsteroidOS/meta-tetra-hybris/blob/2cf2918ba11b0f2915febe97100cb371164c6dfb/recipes-android/android-init/android-init/init.rc#L28
But, looking into the extracted `boot.img` reveals:
```
write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor interactive
```

It turns out that this is the piece of the puzzle! Changing the `ondemand` to `interactive`, mostly fixes the special mode issue!
I say mostly, because it tries to write to sysfs, but fails, due to permission issues. The shipped init script sets permissions for these in `property:dev.bootcomplete=1`:
```
on property:dev.bootcomplete=1
#    write /dev/console [AUTOTEST]BOOT_COMPLETE
    write /sys/module/pwr_mgr/parameters/pm_late_init 1
    write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor interactive
    chown system system /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
    chown system system /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    chown system system /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
    chown system system /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
    chown system system /sys/devices/system/cpu/cpufreq/interactive/timer_rate
    chown system system /sys/devices/system/cpu/cpufreq/interactive/timer_slack
    chown system system /sys/devices/system/cpu/cpufreq/interactive/boostpulse
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/timer_rate
    chmod 660 /sys/devices/system/cpu/cpufreq/interactive/timer_slack
    chmod 220 /sys/devices/system/cpu/cpufreq/interactive/boostpulse
#    start copy_cp_imgs
# Remove boot up MEMC DFS turbo req - ENABLE MEMC DFS by default
    write /sys/power/memc_dfs_init 1
# Disable cpu2 and cpu3
    write /sys/devices/system/cpu/cpu2/online 0
    write /sys/devices/system/cpu/cpu3/online 0
    chmod 0000 /sys/devices/system/cpu/cpu2/online
    chmod 0000 /sys/devices/system/cpu/cpu3/online
```
However, this does not work on AsteroidOS, atleast, not for all of them. Manually changing the permission fixes that issue too.


## Current state
There is some progress, but Always-on-Display still doesn't work :cry: 
When the `FB_BLANK_UNBLANK` or `FB_BLANK_VSYNC_SUSPEND` is called the screen still turns off.
I already tried simple things, like delating the FB_BLANK calls until after `setInteractive` is called, but that didn't work.

But there is something else to look into, we have a different error message related to the display now:
```
Jan 27 19:56:07 tetra kernel: fb_suspend_link_work:368 mutex locked! link not closed
```
Right now my assumption is that something isn't properly disabling the display.


### Sources:
- https://android.googlesource.com/platform/hardware/libhardware/+/master/include/hardware/power.h
- https://github.com/AsteroidOS/mce/commit/65e63d5344a7a45fef627bbd54d143f208cc7695#diff-5423bbeec640a9adc7356be0fd7fb4b34dcb1564b5553302c417328c9c35c9a6R267
- [Shall push some relevant patches later and add links here for reference purposes]

**Comment by FlorentRevest** [comment]
Oh really good debugging MagneFire! Thank you for the writeup this was very interesting.
