### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by gmelchett** [AsteroidOS/meta-tetra-hybris#3]
Current HEAD (7th November) consumes about 35 mA with default settings. (temporary installation)
 - No wlan (default settings)
 - Screen off
 - Wakes from suspend each 5th minute and stays awake < 100ms. IE > 99% suspended

Observations:
 - Loading sensor hub fw does not change the current consumption
 - Android wear in flightmode draws about 1.8 mA (screen off)
 - Removing the "write" to gpio 23 & 28 in init.rc does not help

**Comment by andyrtr** [comment]
https://github.com/alexey6600/mm_sony_tetra_3.14

**Comment by FlorentRevest** [comment]
Fixed by https://github.com/AsteroidOS/meta-tetra-hybris/commit/c77fe7d7db47cdd338e2fc0e47950cee36566912 thanks to a good intuition from Stskeeps.
