### ISSUE TITLE
Vibration not working?

### ISSUE THREAD

**Issue by Rudloff** [AsteroidOS/meta-tetra-hybris#4]
My watch does not vibrate when I get a new notification, even if I force the setting to "Strong vibration" in AsteroidOSSync.

**Comment by FlorentRevest** [comment]
Tetra needs an ffmemless vibration driver. It requires a patch similar to https://github.com/AsteroidOS/meta-bass-hybris/blob/master/recipes-kernel/linux/linux-bass/0004-msm_pwm_vibrator-Convert-timed_output-APIs-to-ff_mem.patch

**Comment by MagneFire** [comment]
Oops, it looks like I forgot to mention this issue in https://github.com/AsteroidOS/meta-asteroid/pull/33. I think this issue can be closed now. @FlorentRevest

**Comment by FlorentRevest** [comment]
Mhh no I think it is a different issue, this watch doesn't seem to depend on either the droid or ffmemless ngfd backends
