### ISSUE TITLE
adb reboot doesn't work

### ISSUE THREAD

**Issue by Valdaer** [AsteroidOS/meta-tetra-hybris#5]
Most importantly `adb reboot bootloader` doesn't work so I can't return to stock android wear or any other ROM. Normal `adb reboot` also doesn't work however except that adb seems to work fine, it lists sony smartwatch when ivoking `adb devices` or I can enter the shell by doing `adb shell`.

Asteroid OS image was downloaded from here: https://asteroidos.org/install/tetra/ and as you can figure out I've done the real installation instead of temporary.

my adb version: 1.0.39

**Comment by FlorentRevest** [comment]
Have you tried using "adb shell reboot bootloader" instead? Or "reboot bootloader" from SSH

**Comment by harshitthakore** [comment]
I have Asus zen watch 3 I just installed astroid os. and adb commands not working.

**Comment by FlorentRevest** [comment]
You should use ssh over usb instead
https://asteroidos.org/wiki/ssh/
And from there run « reboot »
